language: php
php:
    - 5.6
    - 7.2
    - 7.3
    - 7.4
addons:
    sonarcloud:
      organization: webfiori
      token:
        secure: hRhxE7rogVRYMLvE89tRaGSy6ElzbxuMgD+moRK7e24Nz3p/CqnwLuKa4Vpbf91dVAs81uoYc5ZmXIWfmveR3TemmlTTNOAdjK+k6+99zScHfqZw5U/AFxd75HJ3ebVg/SaNkvi65+XkR/Y65nh8QgQQtz3YnhMwXJl5gMn3fmYKp1ddfZLfaui0V7bi5HTfglCJTDe8Pr3PDFpEVfq1DbhhDVfQCRnFIoTuynlWK0NCc1NASlF3uYq0iRN2WX+Dyqj3199PLv1WwaHQ+FrwXobPPKizLexXWYDGls+G54CFMtZM+Mm4aYXs+rUEqTQDXDso54Y/WfRsjYTVK+sZ8k3EUr3FBMkdZnnNM2RN4R/7ofiIesBku2jZwZpex0+ASeVx0zcOYTG3Q30o1oeT391dEo8R2G/Dl49csNC4CaheBHgeLrZenyT9q+PDOKrn8iQljDIk+zlr+TXyxhpUQsryaqkgtyGa81g4s8aUYS42cEGVEP7Q4wfJ/z1eIG1r+7JxoPR9Z6H7EcxxRxQj7p5i2ICddqwXERyBrntmqlxUhl/LkivrDPWdqZPcOEu3ZftKQiLLOY93q9svBmAFIUgAqEy58Uqn8MskXqTMuMp3GZu/aGTgObrmij1iF+smkv7sTrUYT/buBKB4kfIo131mV93NFrYy0e6O6jYn0Uo=
before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev
script:
    - phpunit --verbose --configuration phpunit.xml
after_success:
    - bash <(curl -s https://codecov.io/bash)
    - sonar-scanner